 --Total ln application
 select count (id) as loanapplicant
from financialloan

--MTD LOAN APLICATION
SELECT COUNT (ID) AS MTDLOANAPPLICANT
FROM financialloan
WHERE MONTH(issue_date)=12

--PMTD LOAN APPLICATION
SELECT COUNT(ID) AS PMTDLOANAPPLICATION
FROM financialloan
WHERE MONTH(ISSUE_DATE)=11


--MOM LOAN APPLICATION
WITH CTE AS (
SELECT COUNT (ID) AS MTDLOANAPPLICANT,(SELECT COUNT (iD)  FROM financialloan WHERE MONTH(ISSUE_DATE)=11) AS PMTDLOANAPPLICATION
FROM financialloan
WHERE MONTH(issue_date)=12
)
 SELECT ROUND((MTDLOANAPPLICANT-PMTDLOANAPPLICATION)/CAST(PMTDLOANAPPLICATION AS FLOAT)*100,2) AS MOMLOANAPPLICANT
 FROM CTE
----
--TOTAL FUNDED AMOUNT 
SELECT SUM(LOAN_AMOUNT) AS TOTALFUNDEDAMOUNT 
FROM financialloan

--MTD TOTAL FUNDED AMOUNT 
SELECT SUM(LOAN_AMOUNT) AS MTDTOTALFUNDEDAMOUNT
FROM financialloan
WHERE MONTH(ISSUE_DATE)=12

---PMTD TOTAL FUNDED AMOUNT 
SELECT SUM(LOAN_AMOUNT) AS PMTDTOTALFUNDEDAMOUNT
FROM financialloan
WHERE MONTH(ISSUE_DATE)=11
--- MOM TOTAL FUNDED AMOUNT
WITH CTE AS (
SELECT SUM(LOAN_AMOUNT) AS MTDTOTALFUNDEDAMOUNT,(SELECT SUM(LOAN_AMOUNT) FROM financialloan WHERE MONTH(ISSUE_DATE)=11) AS PMTDTOTALFUNDEDAMOUNT 
FROM financialloan
WHERE MONTH(ISSUE_DATE)=12
)
SELECT ROUND((MTDTOTALFUNDEDAMOUNT-PMTDTOTALFUNDEDAMOUNT)/(CAST(PMTDTOTALFUNDEDAMOUNT AS float))*100,2) AS MOMTOTALFUNDEDAMOUNT
FROM CTE
---TOTAL AMOUNT RECEIVED 
SELECT SUM(TOTAL_PAYMENT) AS TOTALAMOUNTRECEIVED 
FROM financialloan
--MTD TOTAL AMOUNT RECEIVED 
SELECT SUM(TOTAL_PAYMENT) AS MTDTOTALAMOUNTRECEIVED
FROM financialloan
WHERE MONTH(ISSUE_DATE)=12
--PMTD TOTAL AMOUNT RECEIVED 
SELECT SUM(TOTAL_PAYMENT) AS PMTDTOTALAMOUNTRECEIVED
FROM financialloan
WHERE MONTH(ISSUE_DATE)=11
--MOM TOTAL AMOUNT RECEIVED 
WITH CTE AS (
SELECT SUM(TOTAL_PAYMENT) AS MTDTOTALAMOUNTRECEIVED,(SELECT SUM(TOTAL_PAYMENT) FROM financialloan WHERE MONTH(ISSUE_DATE)=11) AS PMTDTOTALAMOUNTRECEIVED
FROM financialloan
WHERE MONTH(ISSUE_DATE)=12
)

SELECT ROUND((MTDTOTALAMOUNTRECEIVED-PMTDTOTALAMOUNTRECEIVED)/(CAST(PMTDTOTALAMOUNTRECEIVED AS FLOAT))*100,2) MOMTOTALAMOUNTRECEIVED
FROM CTE

--AVG INT RATE 
SELECT  ROUND(AVG(INT_RATE)*100,2)AS AVGINTRATE
FROM financialloan
--MTD AVG INT RATE 
SELECT ROUND(AVG(INT_RATE)*100,2)AS MTDAVGINTRATE
FROM financialloan
WHERE MONTH(ISSUE_DATE)=12

--PMTD AVG INT RATE 
SELECT ROUND(AVG(INT_RATE)*100,2)AS PMTDAVGINTRATE
FROM financialloan
WHERE MONTH(ISSUE_DATE)=11
--MOM AVG INT RATE 
WITH CTE AS (
SELECT ROUND(AVG(INT_RATE)*100,2)AS MTDAVGINTRATE,(SELECT ROUND(AVG(INT_RATE)*100,2) FROM financialloan WHERE MONTH(ISSUE_DATE)=11)AS PMTDAVGINTRATE
FROM financialloan
WHERE MONTH(ISSUE_DATE)=12
)
SELECT ROUND((MTDAVGINTRATE-PMTDAVGINTRATE)/(PMTDAVGINTRATE) *100,2) AS MOMAVGINTRATE
FROM CTE
--AVGDTI
SELECT ROUND(AVG(DTI)*100,2) AS AVGDTI
FROM financialloan
--MTDAVGDTI
SELECT ROUND(AVG(DTI)*100,2) AS MTDAVGDTI
FROM financialloan
WHERE MONTH(ISSUE_DATE)=12
--PMTDAVGDTI
SELECT ROUND(AVG(DTI)*100,2) AS PMTDAVGDTI
FROM financialloan
WHERE MONTH(ISSUE_DATE)=11

--MOMAVGDTI
WITH CTE AS (
SELECT ROUND(AVG(DTI)*100,2) AS MTDAVGDTI,(SELECT ROUND(AVG(DTI)*100,2) FROM financialloan WHERE MONTH(ISSUE_DATE)=11) AS PMTDAVGDTI
FROM financialloan
WHERE MONTH(ISSUE_DATE)=12
)
SELECT  ROUND((MTDAVGDTI-PMTDAVGDTI)/(PMTDAVGDTI)*100,2) AS MOMAVGDTI
FROM CTE

--GOOD LOAN APPLICATION 
SELECT COUNT(ID) AS  GOODLOANAPPLICANT
FROM financialloan
WHERE [BAD VS GOOD LOAN]='GOOD'
--BAD LOAN APPLICATION 
SELECT COUNT(ID) AS  GOODLOANAPPLICANT
FROM financialloan
WHERE [BAD VS GOOD LOAN]='BAD'

--PERCENTAGE OF GOOD LOAN APPLICATION 
WITH CTE AS (
SELECT COUNT(ID) AS  GOODLOANAPPLICANT,(SELECT COUNT(ID) FROM financialloan) AS TOTALAPPLICANT
FROM financialloan
WHERE [BAD VS GOOD LOAN]='GOOD'
)

SELECT ROUND((CAST(GOODLOANAPPLICANT AS FLOAT)/CAST(TOTALAPPLICANT AS float)),3)*100 AS GOODLOANPERCENTAGE
FROM CTE

--PERCENTAGE OF BAD LOAN APPLICATION
WITH CTE AS (
SELECT COUNT(ID) AS BADLOANAPPLICANT,(SELECT COUNT(ID) FROM financialloan) AS TOTALAPPLICANT
FROM financialloan
WHERE [BAD VS GOOD LOAN]='BAD'
)

SELECT ROUND((CAST(BADLOANAPPLICANT AS FLOAT)/CAST(TOTALAPPLICANT AS float)),3)*100 AS BADLOANPERCENTAGE
FROM CTE

--GOOD LOAN FUNDED AMOUNT 
SELECT SUM(LOAN_AMOUNT) AS GOODLOANFUNDEDAMT
FROM financialloan
WHERE [BAD VS GOOD LOAN]='GOOD'
--BAD LOAN FUNDED AMOUNT 
SELECT SUM(LOAN_AMOUNT) AS BADLOANFUNDEDAMT
FROM financialloan
WHERE [BAD VS GOOD LOAN]='BAD'

--GOOD LOAN TOTAL RECEIVED PAYMENT
SELECT SUM(total_payment) AS GOODLOANRECEIVEDPAYMENT
FROM financialloan
WHERE [BAD VS GOOD LOAN]='GOOD'

---BAD LOAN TOTAL PAYMENT 
SELECT SUM(TOTAL_PAYMENT)  AS BADLOANRECEIVEDPAYMENT 
FROM financialloan
WHERE [BAD VS GOOD LOAN]='BAD'
-----TOTAL LOAN APPLICATION GROUP BY LOAN STATUS
SELECT LOAN_STATUS, COUNT(ID) AS LOANAPPLICANT
FROM financialloan
GROUP BY loan_status
--TOTAL FUNDED AMOUNT GROUP BY LOAN STATUS
SELECT LOAN_STATUS,SUM(LOAN_AMOUNT)
FROM financialloan
GROUP BY loan_status
---TOTAL RECEIVED AMOUNT BY LOAN STATUS
SELECT LOAN_STATUS,SUM(total_payment)
FROM financialloan
GROUP BY loan_status
--TOTAL LOAN APPLICATION BY MONTH(ISSUES DATE)

SELECT MONTH(ISSUE_DATE) AS MONTH ,COUNT(ID) AS LOANAPPLICANT
FROM financialloan
GROUP BY MONTH(issue_date)
ORDER BY 1

---TOTAL LOAN APPLICANT by REGION
select address_state,count(id) as loanapplicant
from financialloan
group by address_state

---Total loan applicant by loan term
select term,count(id) as loanapplicant 
from financialloan
group by term
-----Total loan applicant by employee lenght 
select emp_length,count(id) as loanapplicant 
from financialloan
group by emp_length

---total loan applicant by loan purpose
select purpose,count(id) as loanapplicant 
from financialloan
group by purpose

--total loan applicant by home ownership
select home_ownership,count(id) as loanapplicant 
from financialloan
group by home_ownership







 
















ALTER TABLE FINANCIALLOAN
ALTER COLUMN LAST_CREDIT_PULL_DATE DATE





SELECT *
FROM financialloan